[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remapping = ["@openzeppelin/=lib/openzeppelin-contracts/", "foundry-devops/=lib/foundry-devops/"]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
